github.com:
    users:
        amolvyas-6:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: amolvyas-6
github.ecodesamsung.com:
    users:
        amolvyas-cs23:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: amolvyas-cs23
